# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'CircularPageControll_Example' do
  pod 'CircularPageControll', :path => '../'

  target 'CircularPageControll_Tests' do
    inherit! :search_paths

    
  end
end
